### ISSUE TITLE
NullReferenceException Error

### ISSUE THREAD

**Issue by Khaladas** [Ludeo/delirium-orb-comparison#2]
After installing .net 3.0 core i am now getting this error : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at delirium.main.Main(String[] args) in C:\Users\lucas\source\repos\delirium\main.cs:line 35

D:\Downloads\DeliriumOrbComparison (1)>delirium.exe
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at delirium.main.Main(String[] args) in C:\Users\lucas\source\repos\delirium\main.cs:line 35

**Comment by Ludeo** [comment]
Hey, I forgot to update the league once again, I published a new release, can you tell me if it works for you now ? ^^

**Comment by Khaladas** [comment]
Yes that fixed it for me thanks!!
