### ISSUE TITLE
Remove hardcoded league name

### ISSUE THREAD

**Issue by Krzysiu** [Ludeo/delirium-orb-comparison#5]
In relation to #4, I advice to remove hardcoded league name and use http://api.pathofexile.com/leagues?type=main&compact=1 instead. Or even better - allow two command line parameters:

1. `--league-names`, which lists leagues, something like `1 - Foo[\r\n]2 - Bar[\r\n]3 - ...`
2. `--league` \ `-l`, which sets league (for keeping it simple and more error prone - expecting league number given by API/previous parameter)

This would temporarily fix #4 and also it would help to make this tool to work across all leagues, including future ones.

**Comment by Ludeo** [comment]
It would be better to do that yea, but I just made this program quickly (mostly for myself) and never touched it again after that because I also stopped playing POE. I will have a look at it

**Comment by Krzysiu** [comment]
I understand - but if you'd someday find a moment, I'll be grateful! Or maybe just compile version with "Standard" for me ;)

**Comment by Ludeo** [comment]
I have integrated the two parameters now and it sets the current league by default (according to the link you've provided). I still have to update each league though because of the Map Variants and each league there will be new map variant so yea, I have to add the League then
